//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionDataUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_system_param
    {
        public string ParamName { get; set; }
        public string Description { get; set; }
        public string ParamValue { get; set; }
        public bool IsJson { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
