//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_verifyCode
    {
        public string Mobile { get; set; }
        public int BusinessType { get; set; }
        public string VerifyCode { get; set; }
        public bool IsUsed { get; set; }
        public int OperationCode { get; set; }
        public int FailsCnter { get; set; }
        public int DayCnter { get; set; }
        public string PicVerifyCode { get; set; }
        public string PicVerifyCodeUrl { get; set; }
        public Nullable<bool> PicIsUsed { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
