//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_shares_seat_order
    {
        public long Id { get; set; }
        public string OrderSN { get; set; }
        public long AccountId { get; set; }
        public int MonthCount { get; set; }
        public int SeatCount { get; set; }
        public long RenewSeatId { get; set; }
        public int Price { get; set; }
        public int PayAmount { get; set; }
        public string ChannelCode { get; set; }
        public long PaymentAccountId { get; set; }
        public int PayStatus { get; set; }
        public string PayStatusDes { get; set; }
        public Nullable<System.DateTime> PaySuccessTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
