//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_app_version
    {
        public long Id { get; set; }
        public string MarketCode { get; set; }
        public string AppVersion { get; set; }
        public int AppVersionOrder { get; set; }
        public int ExamineStatus { get; set; }
        public string WebViewUrl { get; set; }
        public int WaitTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
