//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_broker_account_shares_rel
    {
        public long Id { get; set; }
        public string TradeAccountCode { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public int TotalSharesCount { get; set; }
        public int AccountSharesCount { get; set; }
        public int SimulateSharesCount { get; set; }
        public int AccountCanSoldCount { get; set; }
        public int SimulateCanSoldCount { get; set; }
        public int AccountSellingCount { get; set; }
        public int SimulateSellingCount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
