//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_notice_send_record_details
    {
        public long Id { get; set; }
        public long RecordId { get; set; }
        public string SmsChannelCode { get; set; }
        public string SmsAppKey { get; set; }
        public string ThirdMsgId { get; set; }
        public string Mobile { get; set; }
        public int Status { get; set; }
        public string StatusDes { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
