//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_notice_hold
    {
        public long Id { get; set; }
        public long HoldId { get; set; }
        public int Type { get; set; }
        public long TimeId { get; set; }
        public Nullable<System.DateTime> LastNotifyTime { get; set; }
    }
}
