//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_allot_account
    {
        public long Id { get; set; }
        public long AllotId { get; set; }
        public long AccountId { get; set; }
        public long HoldId { get; set; }
        public long InitialFundAmount { get; set; }
        public long LatestFundAmount { get; set; }
        public int InitialBuyTotalCount { get; set; }
        public int LatestBuyTotalCount { get; set; }
        public long InitialBuyTotalAmount { get; set; }
        public long LatestBuyTotalAmount { get; set; }
        public int InitialCount { get; set; }
        public int LatestCount { get; set; }
        public long InitialRemainDeposit { get; set; }
        public long LatestRemainDeposit { get; set; }
        public long InitialCostPrice { get; set; }
        public long LatestCostPrice { get; set; }
        public long BonusAmount { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
