//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_test_entrust
    {
        public long Id { get; set; }
        public string SharesCode { get; set; }
        public string SharesName { get; set; }
        public string TradeType { get; set; }
        public string StatusDes { get; set; }
        public string EntrustPrice { get; set; }
        public string EntrustCount { get; set; }
        public string EntrustId { get; set; }
        public string DealPrice { get; set; }
        public string DealCount { get; set; }
        public bool IsRead { get; set; }
    }
}
