//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_plate_shares
    {
        public long PlateId { get; set; }
        public string PlateName { get; set; }
        public int PlateType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Market { get; set; }
        public string SharesCode { get; set; }
        public Nullable<long> TotalCapital { get; set; }
        public Nullable<long> CirculatingCapital { get; set; }
        public Nullable<long> PresentPrice { get; set; }
        public Nullable<long> ClosedPrice { get; set; }
        public int SharesType { get; set; }
        public int LimitSharesMarket { get; set; }
        public string LimitSharesCode { get; set; }
        public int ChooseStatus { get; set; }
        public int CalType { get; set; }
        public int WeightMarket { get; set; }
        public string WeightSharesCode { get; set; }
        public int NoWeightMarket { get; set; }
        public string NoWeightSharesCode { get; set; }
        public Nullable<int> PriceType { get; set; }
    }
}
