//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Web_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_shares_baseinfo
    {
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public string SharesName { get; set; }
        public string SharesPyjc { get; set; }
        public int SharesHandCount { get; set; }
        public int MarketStatus { get; set; }
        public int ForbidStatus { get; set; }
        public Nullable<System.DateTime> MarketTime { get; set; }
        public string Business { get; set; }
        public Nullable<long> TotalCapital { get; set; }
        public Nullable<long> CirculatingCapital { get; set; }
        public string Industry { get; set; }
        public string Area { get; set; }
        public string Idea { get; set; }
        public long PresentPrice { get; set; }
        public long ClosedPrice { get; set; }
        public long OpenedPrice { get; set; }
    }
}
