//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharesTradeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_shares_hold
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public long InitialFundAmount { get; set; }
        public long FundAmount { get; set; }
        public int BuyTotalCount { get; set; }
        public long BuyTotalAmount { get; set; }
        public int SoldCount { get; set; }
        public long SoldAmount { get; set; }
        public long SoldProfitAmount { get; set; }
        public int SellingCount { get; set; }
        public int ForceSellingCount { get; set; }
        public int RemainCount { get; set; }
        public int CanSoldCount { get; set; }
        public long InitialDeposit { get; set; }
        public long RemainDeposit { get; set; }
        public long MakeupDeposit { get; set; }
        public long ServiceAmount { get; set; }
        public long ServiceFee { get; set; }
        public System.DateTime LastServiceTime { get; set; }
        public Nullable<System.DateTime> ClosingTime { get; set; }
        public int Status { get; set; }
        public int ClosingForceStatus { get; set; }
        public Nullable<System.DateTime> ClosingForceTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
