//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharesTradeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_broker_account_info_position
    {
        public long Id { get; set; }
        public string AccountCode { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public int TotalSharesCount { get; set; }
        public int CanSoldSharesCount { get; set; }
        public long CostPrice { get; set; }
        public long CurrPrice { get; set; }
        public int BuyCountToday { get; set; }
        public int SellCountToday { get; set; }
        public long MarketValue { get; set; }
        public long ProfitValue { get; set; }
        public int ProfitRate { get; set; }
        public System.DateTime LastModified { get; set; }
        public string SharesName { get; set; }
    }
}
