//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharesHqService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meal_ticketEntities : DbContext
    {
        public meal_ticketEntities()
            : base("name=meal_ticketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_shares_bars> t_shares_bars { get; set; }
        public virtual DbSet<t_shares_bars_index> t_shares_bars_index { get; set; }
        public virtual DbSet<t_shares_bars_index_temp> t_shares_bars_index_temp { get; set; }
        public virtual DbSet<t_shares_bars_temp> t_shares_bars_temp { get; set; }
        public virtual DbSet<t_shares_minutetimedata> t_shares_minutetimedata { get; set; }
        public virtual DbSet<t_shares_minutetimedata_temp> t_shares_minutetimedata_temp { get; set; }
        public virtual DbSet<t_shares_quotes> t_shares_quotes { get; set; }
        public virtual DbSet<t_shares_transactiondata> t_shares_transactiondata { get; set; }
        public virtual DbSet<t_shares_hq_host> t_shares_hq_host { get; set; }
        public virtual DbSet<t_shares_limit_date> t_shares_limit_date { get; set; }
        public virtual DbSet<t_shares_limit_date_group> t_shares_limit_date_group { get; set; }
        public virtual DbSet<t_shares_limit_time> t_shares_limit_time { get; set; }
        public virtual DbSet<t_dim_time> t_dim_time { get; set; }
        public virtual DbSet<t_system_param> t_system_param { get; set; }
        public virtual DbSet<t_shares_quotes_temp> t_shares_quotes_temp { get; set; }
        public virtual DbSet<t_shares_all> t_shares_all { get; set; }
        public virtual DbSet<t_shares_all_corrigendum> t_shares_all_corrigendum { get; set; }
    }
}
