//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Admin_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_cash_record_details
    {
        public long Id { get; set; }
        public long RecordId { get; set; }
        public int Type { get; set; }
        public long ApplyAmount { get; set; }
        public long CashedAmount { get; set; }
        public long ServiceFee { get; set; }
        public long PaymentAccountId { get; set; }
        public string PaymentAccountName { get; set; }
        public string VoucherImg { get; set; }
        public string RefundSn { get; set; }
        public long RechargeId { get; set; }
        public int Status { get; set; }
        public string StatusDes { get; set; }
        public long AdminAccountId { get; set; }
        public string AdminAccountName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
