//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Admin_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_goods
    {
        public long GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string GoodsDescription { get; set; }
        public int GoodsType { get; set; }
        public string GoodsDetails { get; set; }
        public int OrderIndex { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ImgUrl { get; set; }
    }
}
