//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Admin_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_notice_setting
    {
        public long Id { get; set; }
        public string Decription { get; set; }
        public int SendType { get; set; }
        public long SmsTemplateId { get; set; }
        public long SmsSignId { get; set; }
        public int SmsTarget { get; set; }
        public string SmsOtherMobile { get; set; }
        public long PushTemplateId { get; set; }
        public int TimeType { get; set; }
        public string ApiUrl { get; set; }
        public string SendTimeRules { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public string SmsChannelCode { get; set; }
        public string SmsAppKey { get; set; }
        public long SendOverSecond { get; set; }
        public string SmsTriggerAccount { get; set; }
        public string PushTargetTag { get; set; }
    }
}
