//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Admin_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_notice_send_record
    {
        public long Id { get; set; }
        public long SettingId { get; set; }
        public int SendType { get; set; }
        public string SmsChannelCode { get; set; }
        public string SmsAppKey { get; set; }
        public string SmsAppSecret { get; set; }
        public string SmsThirdSignId { get; set; }
        public string SmsThirdTempId { get; set; }
        public int SmsTempType { get; set; }
        public string SmsTempPara { get; set; }
        public string SmsMobile { get; set; }
        public string SendContent { get; set; }
        public bool IsSend { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public System.DateTime MaxSendTime { get; set; }
        public string ErrorMessage { get; set; }
        public string JumpUrl { get; set; }
    }
}
