//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Admin_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sys_conditiontrade_template_buy
    {
        public long Id { get; set; }
        public long TemplateId { get; set; }
        public string Name { get; set; }
        public int ConditionType { get; set; }
        public Nullable<int> ConditionPriceBase { get; set; }
        public Nullable<int> ConditionPriceType { get; set; }
        public Nullable<int> ConditionPriceRate { get; set; }
        public bool IsGreater { get; set; }
        public int EntrustAmount { get; set; }
        public int EntrustType { get; set; }
        public int EntrustPriceGear { get; set; }
        public int ForbidType { get; set; }
        public bool BuyAuto { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool LimitUp { get; set; }
        public int OtherConditionRelative { get; set; }
        public bool IsHold { get; set; }
    }
}
