//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoticeEntities : DbContext
    {
        public NoticeEntities()
            : base("name=NoticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_account_baseinfo> t_account_baseinfo { get; set; }
    
        public virtual int P_Notice_Execute(string apiurl, Nullable<long> accountId, string tempPar)
        {
            var apiurlParameter = apiurl != null ?
                new ObjectParameter("apiurl", apiurl) :
                new ObjectParameter("apiurl", typeof(string));
    
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(long));
    
            var tempParParameter = tempPar != null ?
                new ObjectParameter("tempPar", tempPar) :
                new ObjectParameter("tempPar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Notice_Execute", apiurlParameter, accountIdParameter, tempParParameter);
        }
    }
}
