//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_realname
    {
        public long AccountId { get; set; }
        public string ImgUrlFront { get; set; }
        public string ImgUrlBack { get; set; }
        public string RealName { get; set; }
        public int Sex { get; set; }
        public string BirthDay { get; set; }
        public string CardNo { get; set; }
        public string Address { get; set; }
        public int ExamineStatus { get; set; }
        public string ExamineStatusDes { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ExamineFinishTime { get; set; }
        public string CheckOrg { get; set; }
        public string ValidDateFrom { get; set; }
        public string ValidDateTo { get; set; }
    }
}
