//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_cash_record
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public int ApplyAmount { get; set; }
        public int Amount { get; set; }
        public string CardNumber { get; set; }
        public string BankCode { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string CardBreed { get; set; }
        public int ServiceFeeRate { get; set; }
        public int ServiceFee { get; set; }
        public int Status { get; set; }
        public string StatusDes { get; set; }
        public long AdminAccountId { get; set; }
        public string AdminAccountName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public string OrderSn { get; set; }
        public long MinServiceFee { get; set; }
        public int CashType { get; set; }
    }
}
