//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_recharge_abnormal_refund_record
    {
        public long Id { get; set; }
        public long RecordId { get; set; }
        public string OrderSN { get; set; }
        public string RefundSN { get; set; }
        public long RefundAmount { get; set; }
        public int RefundStatus { get; set; }
        public string RefundFailReason { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
