//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_Handler
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_quotes
    {
        public long Id { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public long PresentPrice { get; set; }
        public long ClosedPrice { get; set; }
        public long OpenedPrice { get; set; }
        public long MaxPrice { get; set; }
        public long MinPrice { get; set; }
        public int TotalCount { get; set; }
        public int PresentCount { get; set; }
        public long TotalAmount { get; set; }
        public int InvolCount { get; set; }
        public int OuterCount { get; set; }
        public long BuyPrice1 { get; set; }
        public int BuyCount1 { get; set; }
        public long BuyPrice2 { get; set; }
        public int BuyCount2 { get; set; }
        public long BuyPrice3 { get; set; }
        public int BuyCount3 { get; set; }
        public long BuyPrice4 { get; set; }
        public int BuyCount4 { get; set; }
        public long BuyPrice5 { get; set; }
        public int BuyCount5 { get; set; }
        public long SellPrice1 { get; set; }
        public int SellCount1 { get; set; }
        public long SellPrice2 { get; set; }
        public int SellCount2 { get; set; }
        public long SellPrice3 { get; set; }
        public int SellCount3 { get; set; }
        public long SellPrice4 { get; set; }
        public int SellCount4 { get; set; }
        public long SellPrice5 { get; set; }
        public int SellCount5 { get; set; }
        public string SpeedUp { get; set; }
        public string Activity { get; set; }
        public System.DateTime LastModified { get; set; }
        public long LimitUpPrice { get; set; }
        public long LimitDownPrice { get; set; }
        public int PriceType { get; set; }
        public int TriPriceType { get; set; }
    }
}
