//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_shares_conditiontrade_buy_trirecord
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public long CreateAccountId { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public string SharesName { get; set; }
        public bool BuyAuto { get; set; }
        public long EntrustId { get; set; }
        public string EntrustErrorDes { get; set; }
        public int SourceFrom { get; set; }
        public long DetailsId { get; set; }
        public Nullable<System.DateTime> TriggerTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long TriAccountId { get; set; }
    }
}
