//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_shares_optional_trend_rel_tri
    {
        public long RelId { get; set; }
        public Nullable<System.DateTime> LastPushTime { get; set; }
        public Nullable<int> LastPushRiseRate { get; set; }
        public Nullable<long> LastPushPrice { get; set; }
        public int TriCountToday { get; set; }
        public int MinPushTimeInterval { get; set; }
        public int MinPushRateInterval { get; set; }
        public long MinTodayPrice { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastPushDesc { get; set; }
    }
}
