//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_account_shares_entrust_manager_dealdetails
    {
        public long Id { get; set; }
        public long EntrustManagerId { get; set; }
        public long DealPrice { get; set; }
        public int DealCount { get; set; }
        public long DealAmount { get; set; }
        public string DealId { get; set; }
        public System.DateTime DealTime { get; set; }
    }
}
