//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_admin_operationLog
    {
        public long LogId { get; set; }
        public long AccountId { get; set; }
        public string AccountName { get; set; }
        public long LoginLogId { get; set; }
        public string OperationCode { get; set; }
        public string OperationDes { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
