//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_broker_account_info_capital
    {
        public string AccountCode { get; set; }
        public long TotalBalance { get; set; }
        public long AvailableBalance { get; set; }
        public long FreezeBalance { get; set; }
        public long WithdrawBalance { get; set; }
        public long MarketValue { get; set; }
        public long TotalValue { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
