//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_helpcenter_question_content
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Answer { get; set; }
        public int OrderIndex { get; set; }
        public bool IsTop { get; set; }
        public int Status { get; set; }
        public bool IsCommon { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
