//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_payment_cash_channel_transfer_account_rel
    {
        public long Id { get; set; }
        public string ChannelCode { get; set; }
        public string BusinessCode { get; set; }
        public long PaymentAccountId { get; set; }
    }
}
