//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_plate_shares_rel_tag_leader
    {
        public long Id { get; set; }
        public int Type { get; set; }
        public long PlateId { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public int LeaderType { get; set; }
    }
}
