//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_platform_wallet_change_record
    {
        public long Id { get; set; }
        public string TypeCode { get; set; }
        public long InCome { get; set; }
        public long Expend { get; set; }
        public long ConfirmDeposit { get; set; }
        public long Context { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
