//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_plate_energyindex_min
    {
        public long Id { get; set; }
        public long PlateId { get; set; }
        public int DayType { get; set; }
        public System.DateTime Time { get; set; }
        public int EnergyIndex { get; set; }
        public int LeaderIndexRate { get; set; }
        public int LeaderIndexScore { get; set; }
        public string LeaderKeyList { get; set; }
        public int PlateLinkageIndexRate { get; set; }
        public int PlateLinkageIndexScore { get; set; }
        public string PlateLinkageKeyList { get; set; }
        public int SharesLinkageIndexRate { get; set; }
        public int SharesLinkageIndexScore { get; set; }
        public string SharesLinkageKeyList { get; set; }
        public int NewHighIndexRate { get; set; }
        public int NewHighIndexScore { get; set; }
        public string NewHighKeyList { get; set; }
        public int PlateVolumeCurrRate { get; set; }
        public int PlateVolumeExceptRate { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
