//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_premium_statistic
    {
        public long Id { get; set; }
        public long ConditionId { get; set; }
        public int PriceType { get; set; }
        public int SharesCountToday { get; set; }
        public int SharesCountYes { get; set; }
        public int PremiumRateToday { get; set; }
        public string PremiumRate3daysPar { get; set; }
        public int PremiumRate3days { get; set; }
        public string PremiumRate5daysPar { get; set; }
        public int PremiumRate5days { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
