//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_marketsentiment_score_date
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public int RealTotalScore { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LimitUpScore { get; set; }
        public int RiseUpScore { get; set; }
        public int LimitUpYesRiseRateScore { get; set; }
        public int LimitUpBombRateScore { get; set; }
        public int LimitDownBombRateScore { get; set; }
        public int HighMarkScore { get; set; }
        public Nullable<int> TotalScore { get; set; }
    }
}
