//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_plate_riserate_last
    {
        public long PlateId { get; set; }
        public int SharesCount { get; set; }
        public long RiseRate { get; set; }
        public long RiseIndex { get; set; }
        public long WeightRiseRate { get; set; }
        public long WeightRiseIndex { get; set; }
        public int RiseLimitCount { get; set; }
        public int DownLimitCount { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
