//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_quotes_riselimit
    {
        public long Id { get; set; }
        public Nullable<long> SharesKey { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public int RiseLimitDays { get; set; }
        public int RiseLimitCount { get; set; }
        public System.DateTime LastRiseLimitTime { get; set; }
        public System.DateTime LastRiseLimitDate { get; set; }
        public bool IsLimitUpToday { get; set; }
        public bool IsLimitUpYesday { get; set; }
        public System.DateTime DataDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public int RiseLimitCountContinue { get; set; }
    }
}
