//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_group_statistic
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> DateKey { get; set; }
        public long ContextId { get; set; }
        public int ContextType { get; set; }
        public int LimitUpCount { get; set; }
        public int LimitDownCount { get; set; }
        public int LimitUpBombCount { get; set; }
        public int LimitDownBombCount { get; set; }
        public int UpCount { get; set; }
        public int DownCount { get; set; }
        public int FlatCount { get; set; }
        public int RiseRate { get; set; }
        public long TotalCount { get; set; }
        public long TotalAmount { get; set; }
        public long TotalCountYestoday { get; set; }
        public long TotalAmountYestoday { get; set; }
        public int LimitUpCountYestoday { get; set; }
        public int LimitDownCountYestoday { get; set; }
        public int LimitUpBombCountYestoday { get; set; }
        public int LimitDownBombCountYestoday { get; set; }
        public int UpCountYestoday { get; set; }
        public int DownCountYestoday { get; set; }
        public int FlatCountYestoday { get; set; }
        public int RiseRateYestoday { get; set; }
        public string SharesKeyYestodayList { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
