//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shares_marketsentiment_baseinfo
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public long GroupTimeKey { get; set; }
        public int LimitUpCount { get; set; }
        public int LimitDownCount { get; set; }
        public int RiseUpCount { get; set; }
        public int RiseDownCount { get; set; }
        public int RiseFlatCount { get; set; }
        public int RiseUpYesCount { get; set; }
        public int LimitUpYesRiseRate { get; set; }
        public int LimitUpBombCount { get; set; }
        public int LimitDownBombCount { get; set; }
        public int HighMarkYesRiseRate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
