//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sms_template
    {
        public long Id { get; set; }
        public string TempName { get; set; }
        public int TempType { get; set; }
        public string TempContent { get; set; }
        public string TempLink { get; set; }
        public int ExamineStatus { get; set; }
        public string ExamineFailReason { get; set; }
        public int Status { get; set; }
        public string ChannelCode { get; set; }
        public string AppKey { get; set; }
        public string ThirdTempId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<System.DateTime> ExamineTime { get; set; }
    }
}
