//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_stock_monitor_tri
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> SharesKey { get; set; }
        public int Market { get; set; }
        public string SharesCode { get; set; }
        public Nullable<System.DateTime> LastPushTime { get; set; }
        public Nullable<int> LastPushRate { get; set; }
        public Nullable<long> LastPushPrice { get; set; }
        public Nullable<int> LastPushType { get; set; }
        public Nullable<int> LastPushMaxRate { get; set; }
        public Nullable<int> LastPushMinRate { get; set; }
        public int MinPushTimeInterval { get; set; }
        public int MinPushMaxRateInterval { get; set; }
        public int MinPushMinRateInterval { get; set; }
        public int MinPushRiseRateInterval { get; set; }
        public int MinPushDownRateInterval { get; set; }
        public int TriCount { get; set; }
        public string PushDesc { get; set; }
        public Nullable<System.DateTime> DataGetTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
