//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_tri_test
    {
        public long Id { get; set; }
        public System.DateTime DataTime { get; set; }
        public Nullable<long> OptionalId { get; set; }
        public Nullable<long> RelId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<int> Market { get; set; }
        public string SharesCode { get; set; }
        public string SharesName { get; set; }
        public Nullable<long> TrendId { get; set; }
        public string TrendName { get; set; }
        public string TrendDescription { get; set; }
        public Nullable<long> TriPrice { get; set; }
        public string TriDesc { get; set; }
        public Nullable<System.DateTime> PushTime { get; set; }
        public Nullable<int> RiseRate { get; set; }
    }
}
