//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealTicket_DBCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_plate_new
    {
        public long PlateId { get; set; }
        public string PlateName { get; set; }
        public int PlateType { get; set; }
        public int CalType { get; set; }
        public int ChooseStatus { get; set; }
        public int BaseStatus { get; set; }
        public int Status { get; set; }
        public int SharesType { get; set; }
        public int LimitSharesMarket { get; set; }
        public string LimitSharesCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int WeightMarket { get; set; }
        public string WeightSharesCode { get; set; }
        public int NoWeightMarket { get; set; }
        public string NoWeightSharesCode { get; set; }
        public Nullable<int> SharesCount { get; set; }
        public Nullable<int> RiseLimitCount { get; set; }
        public Nullable<int> DownLimitCount { get; set; }
        public Nullable<long> WeightRiseIndex { get; set; }
        public Nullable<long> RiseIndex { get; set; }
        public Nullable<long> WeightRiseRate { get; set; }
        public Nullable<long> RiseRate { get; set; }
        public string SharesCode { get; set; }
        public int SharesMarket { get; set; }
        public Nullable<System.DateTime> BaseDate { get; set; }
    }
}
