//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionDataUpdate_NO4
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dim_time
    {
        public int the_date { get; set; }
        public string date_name { get; set; }
        public Nullable<int> the_year { get; set; }
        public string year_name { get; set; }
        public Nullable<int> the_quarter { get; set; }
        public string quarter_name { get; set; }
        public Nullable<int> the_month { get; set; }
        public string month_name { get; set; }
        public Nullable<int> the_week { get; set; }
        public string week_name { get; set; }
        public Nullable<int> week_day { get; set; }
        public string week_day_name { get; set; }
    }
}
